export const players = [
  { name: "reno", tier: 2, image: "reno.png" },
  { name: "doc #10", tier: 2, image: "doc.png" },
  { name: "vami", tier: 3, image: "vami.png" },
  { name: "mara", tier: 3, image: "mara.png" },
  { name: "beli", tier: 2, image: "beli.png" },
  { name: "borna", tier: 2, image: "borna.png" },
  { name: "eli", tier: 3, image: "default.png" },
  { name: "joho", tier: 1, image: "joho.png" },
  { name: "zeko", tier: 2, image: "default.png" },
  { name: "kres", tier: 4, image: "default.png" },
  { name: "zizi", tier: 2, image: "default.png" },
  { name: "toma", tier: 2, image: "toma.png" },
  { name: "điđi", tier: 2, image: "didi.png" },
  { name: "pajo", tier: 3, image: "default.png" },
  { name: "klija", tier: 2, image: "default.png" },
  { name: "toni", tier: 3, image: "default.png" },
  { name: "ervin", tier: 2, image: "default.png" },
  { name: "denis", tier: 1, image: "default.png" },
  { name: "buki", tier: 2, image: "default.png" },
  { name: "benđi", tier: 1, image: "bendji.png" },
  { name: "magda", tier: 1, image: "magda.png" },
];
