export const players = [
  { name: "reno", tier: 2 },
  { name: "doc", tier: 2 },
  { name: "vami", tier: 3 },
  { name: "mara", tier: 3 },
  { name: "beli", tier: 2 },
  { name: "borna", tier: 2 },
  { name: "eli", tier: 3 },
  { name: "joho", tier: 1 },
  { name: "zeko", tier: 2 },
  { name: "kres", tier: 4 },
  { name: "zizi", tier: 2 },
  { name: "toma", tier: 2 },
  { name: "điđi", tier: 2 },
  { name: "pajo", tier: 3 },
  { name: "klija", tier: 2 },
  { name: "toni", tier: 3 },
  { name: "ervin", tier: 2 },
  { name: "denis", tier: 1 },
  { name: "buki", tier: 2 },
];
